name: Set Status Event

on:
  repository_dispatch:
    types: [update_status]

jobs:
  set_status:
    runs-on: ubuntu-latest
    permissions:
      statuses: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Create status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.client_payload.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "${{ github.event.client_payload.state }}",
            "context": "${{ github.event.client_payload.context }}",
            "target_url": "${{ github.event.client_payload.url }}",
            "description": "${{ github.event.client_payload.description }}"
            }' \
          --fail
