# This is a basic workflow to help you get started with Actions

name: Test Token

# Controls when the workflow will run
on:
  pull_request_target:
    branches: ["main"]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# Lint code
  linting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      statuses: write 
      pull-requests: write
    steps:
      - name: echo token
        run : echo ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Set status
        if: always()
        run : |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" \
          --data '{"event_type": "update_status", "client_payload": { \
          "ref": ${{github.ref}} , \
          "sha":${{github.sha}}, \
          "state": ${{ steps.lint_code.conclusion }} , \
          "context": "${{ github.workflow }}/lint" , \
          "description": "Lint code" \
          "url": 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' \
          }' \
          https://api.github.com/repos/${{ github.repository }}/dispatches
          
      - name: set-commit-status
        # You may pin to the exact commit or the version.
        # uses: myrotvorets/set-commit-status-action@5b39333f62641d4fe9c0967572f738a4aea8a15b
        uses: myrotvorets/set-commit-status-action@1.1.4
        with:
          # Authentication token
          token: ${{secrets.REPO_ACCESS_TOKEN }}
          allowForks: true
          sha: ${{github.sha}}
      

    
